<a href="https://colab.research.google.com/github/appling2024/MSP/blob/Liza/%22KeyWords_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U sentence-transformers

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [ ]:
with open('Belkin_IMS_2024_Abstract_rus.txt', 'r', encoding = 'utf-8') as f:
  abstr = f.read()

with open('Belkin_IMS_2024_rus.txt', 'r', encoding = 'utf-8') as file:
  artcl = file.read()

**Yake**

In [ ]:
!pip install git+https://github.com/LIAAD/yake

  Cloning https://github.com/LIAAD/yake to /tmp/pip-req-build-tmz3l_vq
  Running command git clone --filter=blob:none --quiet https://github.com/LIAAD/yake /tmp/pip-req-build-tmz3l_vq
  Resolved https://github.com/LIAAD/yake to commit 0fa58cceb465162b6bd0cab7ec967edeb907fbcc
  Preparing metadata (setup.py) ... done
  Created wheel for yake: filename=yake-0.4.8-py2.py3-none-any.whl size=61995 sha256=abea5574ee77d5c1201988321f1d66941edfc65abe77180a2ffe2591dd4c63df
  Stored in directory: /tmp/pip-ephem-wheel-cache-esa6tok5/wheels/06/e6/1c/8f614adcd4b053020d672b9cbc5ef1166407755a4b71adea0d
Successfully built yake


In [ ]:
import yake

In [ ]:
language = 'ru'
max_ngram_size = 2
numOfKeywords = 10
windowSize = 1

custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, windowsSize=windowSize, top=numOfKeywords, features=None)
keywords = custom_kw_extractor.extract_keywords(abstr)

for kw in keywords:
  print(kw)

#неправильно, ниже другой способ
embedding = model.encode(kw)

similarities = model.similarity(embedding, embedding)
print(similarities)

('Пользовательский фидбек', np.float64(0.03388637525131526))
('частности поликлиниками', np.float64(0.03388637525131526))
('проблемных аспектов', np.float64(0.03388637525131526))
('фидбек является', np.float64(0.0413912416689909))
('является ценным', np.float64(0.0413912416689909))
('ценным источником', np.float64(0.0413912416689909))
('источником информации', np.float64(0.0413912416689909))
('пользовательских отзывов', np.float64(0.07244184621596496))
('отзывов', np.float64(0.09189562580690033))
('оказываемых медицинскими', np.float64(0.09369303761998735))
tensor([[1.0000, 0.1483],
        [0.1483, 1.0000]])


In [ ]:
sentences1_yake = ['Пользовательский фидбек',
'частности поликлиниками',
'проблемных аспектов',
'фидбек является',
'является ценным',
'ценным источником',
'источником информации',
'пользовательских отзывов',
'отзывов',
'оказываемых медицинскими']

In [ ]:
embedding = model.encode(sentences1_yake)
print(embedding.shape) #вывод покажет, что у нас есть 10 векторов, каждый из которых состоит из 384 значений
similarities = model.similarity(embedding, embedding) #вычисление матрицы сходства: где значение == 1Б там элемент равен сам себе, то есть полностью схож сам с собой
print(similarities)

(10, 384)
tensor([[1.0000, 0.5085, 0.6497, 0.7150, 0.4928, 0.5634, 0.6353, 0.7836, 0.6085,
         0.4893],
        [0.5085, 1.0000, 0.5712, 0.4848, 0.5774, 0.6874, 0.6328, 0.5283, 0.4088,
         0.6084],
        [0.6497, 0.5712, 1.0000, 0.5362, 0.6152, 0.7070, 0.6340, 0.7349, 0.6503,
         0.5617],
        [0.7150, 0.4848, 0.5362, 1.0000, 0.6649, 0.5188, 0.5369, 0.5588, 0.5701,
         0.4519],
        [0.4928, 0.5774, 0.6152, 0.6649, 1.0000, 0.8648, 0.5813, 0.4612, 0.5275,
         0.5038],
        [0.5634, 0.6874, 0.7070, 0.5188, 0.8648, 1.0000, 0.7532, 0.5330, 0.5364,
         0.6391],
        [0.6353, 0.6328, 0.6340, 0.5369, 0.5813, 0.7532, 1.0000, 0.5600, 0.5100,
         0.7069],
        [0.7836, 0.5283, 0.7349, 0.5588, 0.4612, 0.5330, 0.5600, 1.0000, 0.7352,
         0.6237],
        [0.6085, 0.4088, 0.6503, 0.5701, 0.5275, 0.5364, 0.5100, 0.7352, 1.0000,
         0.5830],
        [0.4893, 0.6084, 0.5617, 0.4519, 0.5038, 0.6391, 0.7069, 0.6237, 0.5830,
         1.0000]])

In [ ]:
language = 'ru'
max_ngram_size = 2
numOfKeywords = 10
windowSize = 1

custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, windowsSize=windowSize, top=numOfKeywords, features=None)
keywords = custom_kw_extractor.extract_keywords(artcl)

for kw in keywords:
  print(kw)

('данных', np.float64(0.009095100803960017))
('отзывов', np.float64(0.01960489593283744))
('данные', np.float64(0.024541701737508533))
('отзывы', np.float64(0.026001123846662002))
('анализа тональности', np.float64(0.02732946883684851))
('набор данных', np.float64(0.03038649897920946))
('пользователей', np.float64(0.030754829425824626))
('тональности', np.float64(0.037784819669004883))
('количество', np.float64(0.03886993534896546))
('отзывах', np.float64(0.04581876636436414))


In [ ]:
sentences2_yake = ['данных',
'отзывов',
'данные',
'отзывы',
'анализа тональности',
'набор данных',
'пользователей',
'тональности',
'количество',
'отзывах']

In [ ]:
embedding = model.encode(sentences2_yake)
print(embedding.shape)

similarities = model.similarity(embedding, embedding)
print(similarities)

(10, 384)
tensor([[1.0000, 0.5492, 0.9044, 0.5815, 0.4363, 0.8740, 0.3898, 0.4762, 0.4112,
         0.6451],
        [0.5492, 1.0000, 0.5575, 0.8853, 0.5137, 0.5583, 0.6333, 0.5039, 0.6104,
         0.8279],
        [0.9044, 0.5575, 1.0000, 0.5990, 0.4961, 0.8612, 0.4617, 0.5523, 0.4717,
         0.5254],
        [0.5815, 0.8853, 0.5990, 1.0000, 0.5108, 0.5599, 0.5398, 0.5070, 0.6170,
         0.8820],
        [0.4363, 0.5137, 0.4961, 0.5108, 1.0000, 0.5054, 0.7369, 0.8665, 0.6053,
         0.4938],
        [0.8740, 0.5583, 0.8612, 0.5599, 0.5054, 1.0000, 0.5101, 0.5527, 0.5251,
         0.6038],
        [0.3898, 0.6333, 0.4617, 0.5398, 0.7369, 0.5101, 1.0000, 0.6637, 0.6592,
         0.5349],
        [0.4762, 0.5039, 0.5523, 0.5070, 0.8665, 0.5527, 0.6637, 1.0000, 0.6833,
         0.4797],
        [0.4112, 0.6104, 0.4717, 0.6170, 0.6053, 0.5251, 0.6592, 0.6833, 1.0000,
         0.6311],
        [0.6451, 0.8279, 0.5254, 0.8820, 0.4938, 0.6038, 0.5349, 0.4797, 0.6311,
         1.0000]])

**KeyBert**

In [ ]:
!pip install keybert

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 1.7 MB/s eta 0:00:00


In [ ]:
import keybert
from keybert import KeyBERT

In [ ]:
kw_model = KeyBERT()

In [ ]:
keywords_abs = kw_model.extract_keywords(abstr, keyphrase_ngram_range=(1, 2), top_n = 10)
keywords_abs

[('источником информации', 0.5347),
 ('медицинских учреждениях', 0.4951),
 ('медицинскими учреждениями', 0.4907),
 ('ценным источником', 0.4825),
 ('тематического моделирования', 0.4818),
 ('повышения удовлетворенности', 0.4651),
 ('поликлиниками выявления', 0.4513),
 ('оказываемых медицинскими', 0.4474),
 ('отзывов медицинских', 0.444),
 ('информации', 0.4434)]

In [ ]:
sentences_abstr_bert = ['источником информации',
 'медицинских учреждениях',
 'медицинскими учреждениями',
 'ценным источником',
 'тематического моделирования',
 'повышения удовлетворенности',
 'поликлиниками выявления',
 'оказываемых медицинскими',
 'отзывов медицинских',
 'информации']

In [ ]:
embedding = model.encode(sentences_abstr_bert)
print(embedding.shape)
similarities = model.similarity(embedding, embedding)
print(similarities)

(10, 384)
tensor([[1.0000, 0.6545, 0.6868, 0.7532, 0.6138, 0.6149, 0.5979, 0.7069, 0.7338,
         0.9557],
        [0.6545, 1.0000, 0.8998, 0.6253, 0.7373, 0.7311, 0.7083, 0.7498, 0.7863,
         0.6632],
        [0.6868, 0.8998, 1.0000, 0.6792, 0.7891, 0.7328, 0.7410, 0.7599, 0.7209,
         0.6685],
        [0.7532, 0.6253, 0.6792, 1.0000, 0.6460, 0.6485, 0.6046, 0.6391, 0.6630,
         0.7211],
        [0.6138, 0.7373, 0.7891, 0.6460, 1.0000, 0.7853, 0.6950, 0.6236, 0.6548,
         0.5893],
        [0.6149, 0.7311, 0.7328, 0.6485, 0.7853, 1.0000, 0.7419, 0.5292, 0.6432,
         0.6154],
        [0.5979, 0.7083, 0.7410, 0.6046, 0.6950, 0.7419, 1.0000, 0.6269, 0.5823,
         0.6039],
        [0.7069, 0.7498, 0.7599, 0.6391, 0.6236, 0.5292, 0.6269, 1.0000, 0.8997,
         0.6969],
        [0.7338, 0.7863, 0.7209, 0.6630, 0.6548, 0.6432, 0.5823, 0.8997, 1.0000,
         0.7364],
        [0.9557, 0.6632, 0.6685, 0.7211, 0.5893, 0.6154, 0.6039, 0.6969, 0.7364,
         1.0000]])

In [ ]:
keywords_art = kw_model.extract_keywords(artcl, keyphrase_ngram_range=(1, 2), top_n = 10)
keywords_art

[('взаимодействия предотвращение', 0.5012),
 ('привлечения пользователей', 0.4918),
 ('медучреждениям пользователи', 0.4897),
 ('пользователей информацию', 0.4789),
 ('сообщения некоторых', 0.4776),
 ('стремительного развития', 0.469),
 ('сообщениях разнообразные', 0.4688),
 ('что информация', 0.4667),
 ('пользователями учреждениям', 0.4666),
 ('автоматического определения', 0.4624)]

In [ ]:
sentence_artcl_bert = ['взаимодействия предотвращение',
 'привлечения пользователей',
 'медучреждениям пользователи',
 'пользователей информацию',
 'сообщения некоторых',
 'стремительного развития',
 'сообщениях разнообразные',
 'что информация',
 'пользователями учреждениям',
 'автоматического определения']

In [ ]:
embeddings = model.encode(sentence_artcl_bert)
print(embeddings.shape)
similarities = model.similarity(embeddings, embeddings)
print(similarities)

(10, 384)
tensor([[1.0000, 0.7820, 0.7911, 0.5661, 0.7123, 0.7900, 0.7650, 0.6553, 0.7887,
         0.7616],
        [0.7820, 1.0000, 0.9312, 0.6922, 0.6684, 0.8061, 0.7495, 0.6615, 0.8936,
         0.7311],
        [0.7911, 0.9312, 1.0000, 0.7009, 0.6756, 0.8206, 0.7628, 0.6913, 0.9367,
         0.7578],
        [0.5661, 0.6922, 0.7009, 1.0000, 0.5362, 0.5845, 0.6008, 0.7798, 0.6696,
         0.5123],
        [0.7123, 0.6684, 0.6756, 0.5362, 1.0000, 0.6714, 0.8449, 0.7456, 0.6688,
         0.7283],
        [0.7900, 0.8061, 0.8206, 0.5845, 0.6714, 1.0000, 0.7930, 0.6753, 0.8216,
         0.7789],
        [0.7650, 0.7495, 0.7628, 0.6008, 0.8449, 0.7930, 1.0000, 0.7145, 0.7637,
         0.6851],
        [0.6553, 0.6615, 0.6913, 0.7798, 0.7456, 0.6753, 0.7145, 1.0000, 0.6789,
         0.7512],
        [0.7887, 0.8936, 0.9367, 0.6696, 0.6688, 0.8216, 0.7637, 0.6789, 1.0000,
         0.7558],
        [0.7616, 0.7311, 0.7578, 0.5123, 0.7283, 0.7789, 0.6851, 0.7512, 0.7558,
         1.0000]])

Авторский список ключевых слов: отзывы пациентов поликлиник; открытые данные; Яндекс Карты; веб-скрапинг; естественная обработка языка; анализ тональности; тематическое моделирование

Результаты автоматического выделения КС
Yake:
В аннотации было выделено 1 похожее ключевое слово: пользовательские отзывы.
В самой статье было выделено 4 похожих КС: анализ тональности, набор данных, отзывы, пользователи.

KeyBert:
Аннотация: тематическое моделирование.
Статья: 0.

Результаты показывают, что процесс автоматического выделения ключевых слов выдал неудовлетворительные результаты и требует редакции вручную.