In [2]:
import numpy as np
my_lst = [1, 2, 3]
arr1 = np.array(my_lst)
print(arr1)
arr2 = np.ones((3,10), dtype=int)
print(arr2)
arr3 = np.arange(1,31)
print(arr3)
arr33 = np.arange(0, 16, 5)
print(arr33)
arr34 = np.arange(5)
print(arr34)
arr3 = arr3.reshape(3, 10)
print(arr3)
arr4 = np.arange(1,31).reshape(3, 10)
print(arr4)
arr5 = np.ones((3,10), dtype=int)
arr5 = arr5 * 100
print(arr5)
arr6 = arr4 + arr5
print(arr6)

[1 2 3]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[ 0  5 10 15]
[0 1 2 3 4]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]
[[101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]]


In [10]:
task1 = np.ones((6,4), dtype=int)
task1 = task1 * 5
print(task1)
task2 = np.arange(1,25).reshape(3, 8)
print(task2)
task2 = np.arange(1,25).reshape(6, 4)
print(task2)
task_sum = task1+task2
print(task_sum)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]


In [22]:
task3 = np.arange(100, 1300, 100).reshape(3, 4)
print(task3)
task4 = np.arange(1, 13).reshape(3, 4)
print(task4)
umno = task3*task4
print(umno)

[[ 100  200  300  400]
 [ 500  600  700  800]
 [ 900 1000 1100 1200]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  100   400   900  1600]
 [ 2500  3600  4900  6400]
 [ 8100 10000 12100 14400]]


In [55]:
arr3 = np.arange(1,31).reshape(3, 10)
print(arr3)
print("\nПервая строка:")
print(arr3[ 0, :])
print("\nПервый столбец:")
print(arr3[ :, 0])
last_two_columns = arr3[:, -2:]
print("\nДва последних столбца:")
print(last_two_columns)
top_left_square = arr3[:2, :2]
print("\nЛевый верхний квадратик 2×2:")
print(top_left_square)
top_left_square_alt = arr3[:2, :2]
print("\nЛевый верхний квадратик 2×2:")
print(top_left_square_alt)
bottom_right_square = arr3[-2:, -2:]
print("\nПравый нижний квадратик 2×2:")
print(bottom_right_square)
arr3[:, 1::2] = 77 
print("\nМассив после замены чётных столбцов на 77:")
print(arr3)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

Первая строка:
[ 1  2  3  4  5  6  7  8  9 10]

Первый столбец:
[ 1 11 21]

Два последних столбца:
[[ 9 10]
 [19 20]
 [29 30]]

Левый верхний квадратик 2×2:
[[ 1  2]
 [11 12]]

Левый верхний квадратик 2×2:
[[ 1  2]
 [11 12]]

Правый нижний квадратик 2×2:
[[19 20]
 [29 30]]

Массив после замены чётных столбцов на 77:
[[ 1 77  3 77  5 77  7 77  9 77]
 [11 77 13 77 15 77 17 77 19 77]
 [21 77 23 77 25 77 27 77 29 77]]


In [49]:
chess = np.zeros((8,8), dtype=int)
chess[1::2, ::2] = 1
chess[::2, 1::2] = 1
print(chess)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
matrix = np.zeros((10, 10), dtype=int)
for i in range(1, 10):  
    for j in range(i):  
        matrix[i, j] = 5
print(matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0 0]
 [5 5 0 0 0 0 0 0 0 0]
 [5 5 5 0 0 0 0 0 0 0]
 [5 5 5 5 0 0 0 0 0 0]
 [5 5 5 5 5 0 0 0 0 0]
 [5 5 5 5 5 5 0 0 0 0]
 [5 5 5 5 5 5 5 0 0 0]
 [5 5 5 5 5 5 5 5 0 0]
 [5 5 5 5 5 5 5 5 5 0]]


In [ ]:
matrix = np.zeros((10, 10), dtype=int)
number = 1
for i in range(1, 10): 
    for j in range(i): 
        matrix[i, j] = number
        number += 1
print("Матрица с числами ниже диагонали:")
print(matrix)

Матрица с числами ниже диагонали:
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 2  3  0  0  0  0  0  0  0  0]
 [ 4  5  6  0  0  0  0  0  0  0]
 [ 7  8  9 10  0  0  0  0  0  0]
 [11 12 13 14 15  0  0  0  0  0]
 [16 17 18 19 20 21  0  0  0  0]
 [22 23 24 25 26 27 28  0  0  0]
 [29 30 31 32 33 34 35 36  0  0]
 [37 38 39 40 41 42 43 44 45  0]]


In [ ]:
matrix = np.zeros((10, 10), dtype=int)
number = 1
for j in range(10):  
    for i in range(j + 1, 10):  
        matrix[i, j] = number
        number += 1
print("Матрица с числами ниже диагонали (по столбцам):")
print(matrix)

Матрица с числами ниже диагонали (по столбцам):
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 2 10  0  0  0  0  0  0  0  0]
 [ 3 11 18  0  0  0  0  0  0  0]
 [ 4 12 19 25  0  0  0  0  0  0]
 [ 5 13 20 26 31  0  0  0  0  0]
 [ 6 14 21 27 32 36  0  0  0  0]
 [ 7 15 22 28 33 37 40  0  0  0]
 [ 8 16 23 29 34 38 41 43  0  0]
 [ 9 17 24 30 35 39 42 44 45  0]]
